version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bigdeal-backend
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./uploads:/app/uploads
    environment:
      # Database settings (using RDS)
      - DB_HOST=bigdeal-backend.cqr4agac0wca.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456789
      - DB_NAME=BigdealBackend
      - DB_SSL=true
      
      # Server settings
      - NODE_ENV=production
      - PORT=3002
      
      # JWT settings
      - JWT_SECRET=bigdeal-super-secret-key
      - JWT_EXPIRES_IN=7d
      
      # Upload directory
      - UPLOAD_DIR=uploads 